### ISSUE TITLE
AddValidatorsFromAssemblyContaining not working

### ISSUE THREAD

**Issue by cmrabet** [FluentValidation/FluentValidation.AspNetCore#16]
### FluentValidation.AspNetCore version

11.2.2

### FluentValidation version

11.3.0

### ASP.NET version

.NET 6

### Summary

When I register Fluent Validation from my Service extension with `AddFluentValidation` as follows, it works:

```csharp
public static class ServicesExtension
{
    public static IServiceCollection ConfigureApplication(this IServiceCollection services)
    {
        services.AddMediatR(typeof(ServicesExtension));
       services.AddFluentValidation(options => {
            options.RegisterValidatorsFromAssemblyContaining<CreateOrder>();
        });
        return services;
    }
}
```

However, I get the following warning:

`warning CS0618: 'FluentValidationMvcExtensions.AddFluentValidation(IServiceCollection, Action<FluentValidationMvcConfiguration>)' is obsolete: 'Calling AddFluentValidation() is deprecated. Call services.AddFluentValidationAutoValidation().AddFluentValidationClientsideAdapters() instead, which has the same effect. For details see https://github.com/FluentValidation/FluentValidation/issues/1965`

When I follow the instructions from the warning and I use `AddValidatorsFromAssemblyContaining` as follows:

```csharp
public static class ServicesExtension
{
    public static IServiceCollection ConfigureApplication(this IServiceCollection services)
    {
        services.AddMediatR(typeof(ServicesExtension));
        services.AddValidatorsFromAssemblyContaining<CreateOrder>();
        return services;
    }
}
```

The warning is gone, but the validation is not working anymore.

I've also tried doing this, doesn't work either:

```csharp
...
services.AddValidatorsFromAssemblyContaining<CreateOrder.Validator>();
...
```

Here is how I'm registering the service extension from my Program.cs:

```csharp
using erp.api.Middleware;
using erp.application;
using erp.infrastructure;

var builder = WebApplication.CreateBuilder(args);
{
    builder.Services
        .ConfigureApplication()
        .ConfigureInfrastructure()
        .AddControllers();
}

var app = builder.Build();
{
    app.UseMiddleware<ErrorMiddleware>();
    //app.UseHttpsRedirection();
    app.MapControllers();
    app.Run();
}
```

Also, I'm using CQRS with Mediatr, here is the class that implements the Validator I use for registration:

```csharp
using erp.infrastructure.Persistence.Interfaces;
using FluentValidation;
using Mapster;
using MediatR;

namespace erp.application.Orders.Commands;

public class CreateOrder
{
    public class Command : IRequest<OrderDto>
    {
        public OrderCreateDto Order { get; set; } = null!;
    }

    public class Validator : AbstractValidator<OrderCreateDto>
    {
        public Validator()
        {
            RuleFor(x => x.Account).NotEmpty();
        }
    }

    public class Handler : IRequestHandler<Command, OrderDto>
    {
        private readonly IOrderRepository _orderRepo;

        public Handler(IOrderRepository orderRepo)
        {
            _orderRepo = orderRepo;
        }

        public async Task<OrderDto> Handle(Command request, CancellationToken cancellationToken)
        {
            var newOrder = await _orderRepo.CreateOne(request.Order.Account);
            return newOrder.Adapt<OrderDto>();
        }
    }
}
``` 

### Steps to Reproduce

Explained in the previous section

**Comment by JeremySkinner** [comment]
The `AddFluentValidation` call from your original code does 3 things: 
- Enables automatic validation 
- Enables clientside validation adapters
- Scans the specified assembly to register validators 

As per the message in the warning you’re getting, you need to call the appropriate methods to enable auto-validation and clientside adaptors in order to achieve the same functionality (`AddFluentValidationAutoValidation()` and `AddFluentValidationClientsideAdapters()`) as well as registering the validators.  

So with the current equivalent version the equivalent would be to make the following 3 method calls sequentially:

```csharp
services.AddFluentValidationAutoValidation();
services.AddFluentValidationClientsideAdapters();
services.AddValidatorsFromAssemblyContaining<CreateOrder>();
```

In fact the old `AddFluentValidation` method is just making these same 3 calls internally. This is covered in the readme for this repo -
please have a read through it if you haven’t already as it explains what each of these methods does. 

If, after making this change, things still aren’t working as expected then there’s likely something incorrect elsewhere in your project. To troubleshoot I’d suggest creating a small, minimal sample project that reproduces the issue. If after doing this you still believe the issue lies with FluentValidation and not with something in your own project then please re-open the issue and provide the sample project to reproduce.

**Comment by cmrabet** [comment]
@JeremySkinner thanks, that worked.

I didn't understand from the documentation that I had to use all those methods; I thought that I had to use one, based on how I wanted to register the service (auto, manual, custom validator, etc..). I'll read the documentation again more carefully this time.

Thanks for your help.

**Comment by JeremySkinner** [comment]
I've updated the issue linked from the compiler warning to contain a clearer example, so hopefully that will help anyone else migrating too: https://github.com/FluentValidation/FluentValidation/issues/1965

**Comment by cmrabet** [comment]
> I've updated the issue linked from the compiler warning to contain a clearer example, so hopefully that will help anyone else migrating too: [FluentValidation/FluentValidation#1965](https://github.com/FluentValidation/FluentValidation/issues/1965)

I really appreciate it, thanks!!
