### ISSUE TITLE
Unexpected logging on validation failure

### ISSUE THREAD

**Issue by banderberg** [FluentValidation/FluentValidation.AspNetCore#2]
### FluentValidation.AspNetCore version

11.1.2

### FluentValidation version

N/A

### ASP.NET version

.NET 6

### Summary

Running inside an AWS Lambda, calling ValidateAndThrowAsync, when validation of an email address fails there is a log sent to AWS CloudWatch:

`-- EmailAddress: 'Email Address' is not a valid email address. Severity: Error`

This is not coming from my code.  How can I disable logging, or alternatively configure it to log in JSON format?

We have another Lambda that handles our logs that expects everything to be in JSON so the log above is breaking that lambda.

Thanks

### Steps to Reproduce

Validate an email address in AWS Lambda.

**Comment by JeremySkinner** [comment]
Calling `ValidateAndThrowAsync` throws an exception. How this exception is handled, processed and logged is not controlled by FluentValidation - *it is up to your application to catch the exception and then process/log it as you require*. If you don't catch/process the exception, then Lambda will treat it as unhandled and simply log it as a string. 

Alternatively instead of throwing an exception, call `ValidateAsync` instead which returns a `ValidationResult` which you can process/serialise/log as you require. 

Please note for future reference this is an issue tracker for reporting bugs in the FluentValidation.AspNetCore library - [it is not for general support/usage questions.](https://github.com/FluentValidation/FluentValidation.AspNetCore/blob/main/.github/CONTRIBUTING.md#general-support-feedback-and-discussions)

**Comment by banderberg** [comment]
Something is amiss then - our application throws other exceptions out of the lambda, and those are logged as JSON.

**Comment by JeremySkinner** [comment]
I'm afraid that is something you'll need to debug for yourself. As it isn't something that's being done by FluentValidation this isn't something that I can help with. 

The text that you're seeing in the log is the standard `ToString()` representation of a `ValidationException`, suggesting that there is nothing handling the exception when it's being thrown, falling back to lambda's default unhandled exception behaviour. 

As a starting point I'd suggest you begin troubleshooting by creating a minimal sample project reproduces the issue, stripping out anything unrelated.

**Comment by banderberg** [comment]
Thanks for your time Jeremy.
